version: '3'

volumes:
  nextcloud:  
    
services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=mysqlpasswd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:fpm
    container_name: nextcloud_nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html     
      - ./nextcloud/data:/var/www/data
    environment:
      - MYSQL_PASSWORD=mysqlpasswd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_DATA_DIR=/var/www/data
      - REDIS_HOST=redis
       
  redis:
    image: "redis:latest"
    container_name: nextcloud_redis
    restart: always  
  
  web:
    image: nginx
    container_name: nextcloud_nginx
    restart: always
    ports:
      - 8080:8080
    links:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert:/etc/ssl:ro
      - ./nginx/logs:/var/log/nginx
    volumes_from:
      - app
        